In [3]:
# Dataset: https://www.kaggle.com/datasets/rmisra/news-category-dataset

In [4]:
import pandas as pd
import tensorflow as tf
import numpy as np

### Date gathering

In [5]:
data = pd.read_json('News_Category_Dataset_v3.json', lines=True)

### Data exploration

In [6]:
data

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22
...,...,...,...,...,...,...
209522,https://www.huffingtonpost.com/entry/rim-ceo-t...,RIM CEO Thorsten Heins' 'Significant' Plans Fo...,TECH,Verizon Wireless and AT&T are already promotin...,"Reuters, Reuters",2012-01-28
209523,https://www.huffingtonpost.com/entry/maria-sha...,Maria Sharapova Stunned By Victoria Azarenka I...,SPORTS,"Afterward, Azarenka, more effusive with the pr...",,2012-01-28
209524,https://www.huffingtonpost.com/entry/super-bow...,"Giants Over Patriots, Jets Over Colts Among M...",SPORTS,"Leading up to Super Bowl XLVI, the most talked...",,2012-01-28
209525,https://www.huffingtonpost.com/entry/aldon-smi...,Aldon Smith Arrested: 49ers Linebacker Busted ...,SPORTS,CORRECTION: An earlier version of this story i...,,2012-01-28
209526,https://www.huffingtonpost.com/entry/dwight-ho...,Dwight Howard Rips Teammates After Magic Loss ...,SPORTS,The five-time all-star center tore into his te...,,2012-01-28

In [7]:
data.shape

(209527, 6)

In [8]:
data.columns

Index(['link', 'headline', 'category', 'short_description', 'authors', 'date'], dtype='str')

In [ ]:
# We need only the short description for our next word prediction task. So we will drop the other columns.
data = data[['short_description']]

In [13]:
data

                                        short_description
0       Health experts said it is too early to predict...
1       He was subdued by passengers and crew when he ...
2       "Until you have a dog you don't understand wha...
3       "Accidentally put grown-up toothpaste on my to...
4       Amy Cooper accused investment firm Franklin Te...
...                                                   ...
209522  Verizon Wireless and AT&T are already promotin...
209523  Afterward, Azarenka, more effusive with the pr...
209524  Leading up to Super Bowl XLVI, the most talked...
209525  CORRECTION: An earlier version of this story i...
209526  The five-time all-star center tore into his te...

[209527 rows x 1 columns]

### Check null and duplicate columns and remove it

In [15]:
# Check null values
data.isnull().sum()

short_description    0
dtype: int64

In [16]:
# Check duplicates
data.duplicated().sum()

np.int64(22505)

In [ ]:
# Drop duplicates
data.drop_duplicates(inplace=True)

In [18]:
# Check duplicates after remove it
data.duplicated().sum()

np.int64(0)